Repository domaframework/doma, pull requests merged in 2024-03, with the labels that each got.

#1077 Insert the TOP clause in the correct position
  doma-core/src/main/java/org/seasar/doma/internal/jdbc/dialect/Mssql2008PagingTransformer.java
  doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/NodePreparedSqlBuilder.java
  doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/SimpleSqlNodeVisitor.java
  doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/SqlParser.java
  doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/SqlTokenType.java
  doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/SqlTokenizer.java
  doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/node/DistinctNode.java
  doma-core/src/main/java/org/seasar/doma/jdbc/SqlNodeVisitor.java
  doma-core/src/test/java/org/seasar/doma/internal/jdbc/dialect/Mssql2008PagingTransformerTest.java
  integration-test-java/src/main/java/org/seasar/doma/it/dao/EmployeeDao.java
  integration-test-java/src/main/resources/META-INF/org/seasar/doma/it/dao/EmployeeDao/selectDistinctAll.sql
  integration-test-java/src/test/java/org/seasar/doma/it/sqlfile/SqlFileSelectPagingTest.java
Labels: fix

#1079 Fix MysqlUpsertAssembler for support MySQL8
  doma-core/src/main/java/org/seasar/doma/jdbc/dialect/MysqlDialect.java
  doma-core/src/main/java/org/seasar/doma/jdbc/dialect/MysqlUpsertAssembler.java
Labels: feature

#1083 Update documents
  CONTRIBUTING.md
  README.md
Labels: chore

#1084 Update JDK version
  CONTRIBUTING.md
Labels: docs

#1085 Resolve warning
  doma-core/src/test/java/org/seasar/doma/jdbc/query/UpsertAssemblerContextTest.java
Labels: chore

#1087 Support Java 22
  .github/workflows/ci.yml
  README.md
Labels: chore
