Repository domaframework/doma, pull requests merged in 2024-05, with the labels that each got.

#1105 Specify required settings for Maven project in Eclipse
  README.md
Labels: docs

#1106 Change to not specify conflict_target by default for ON CONFLICT DO NOTHING
  doma-core/src/main/java/org/seasar/doma/BatchInsert.java
  doma-core/src/main/java/org/seasar/doma/Insert.java
  doma-core/src/main/java/org/seasar/doma/jdbc/criteria/context/Operand.java
  doma-core/src/main/java/org/seasar/doma/jdbc/criteria/statement/NativeSqlUpsertTerminal.java
  doma-core/src/main/java/org/seasar/doma/jdbc/dialect/H2UpsertAssembler.java
  doma-core/src/main/java/org/seasar/doma/jdbc/dialect/MssqlUpsertAssembler.java
  doma-core/src/main/java/org/seasar/doma/jdbc/dialect/MysqlUpsertAssembler.java
  doma-core/src/main/java/org/seasar/doma/jdbc/dialect/OracleUpsertAssembler.java
  doma-core/src/main/java/org/seasar/doma/jdbc/dialect/PostgreSqlUpsertAssembler.java
  doma-core/src/main/java/org/seasar/doma/jdbc/query/AutoBatchInsertQuery.java
  doma-core/src/main/java/org/seasar/doma/jdbc/query/AutoInsertQuery.java
  doma-core/src/main/java/org/seasar/doma/jdbc/query/QueryOperand.java
  doma-core/src/main/java/org/seasar/doma/jdbc/query/QueryOperandPair.java
  doma-core/src/main/java/org/seasar/doma/jdbc/query/UpsertAssemblerContext.java
  doma-core/src/main/java/org/seasar/doma/jdbc/query/UpsertAssemblerContextBuilder.java
  doma-core/src/main/java/org/seasar/doma/jdbc/query/UpsertSetValue.java
  doma-core/src/test/java/org/seasar/doma/jdbc/query/UpsertAssemblerContextBuilderTest.java
  doma-core/src/test/java/org/seasar/doma/jdbc/query/UpsertAssemblerContextTest.java
  doma-kotlin/src/test/kotlin/org/seasar/doma/jdbc/criteria/KEntityqlBatchInsertTest.kt
  doma-kotlin/src/test/kotlin/org/seasar/doma/jdbc/criteria/KEntityqlInsertTest.kt
  doma-kotlin/src/test/kotlin/org/seasar/doma/jdbc/criteria/KNativeSqlInsertTest.kt
Labels: fix

#1107 Cache all TypeElement instances in Annotation Processing
  doma-processor/src/main/java/org/seasar/doma/internal/apt/MoreElements.java
Labels: perf

#1102 Create UserDefinedExpression feature
  doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/Expressions.java
  doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/UserDefinedExpression.java
  doma-core/src/main/java/org/seasar/doma/jdbc/criteria/query/BuilderSupport.java
  doma-core/src/test/java/org/seasar/doma/jdbc/criteria/NativeSqlSelectTest.java
  doma-core/src/test/java/org/seasar/doma/jdbc/criteria/expression/ExpressionsTest.java
  doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/expression/KExpressions.kt
  doma-kotlin/src/test/kotlin/org/seasar/doma/jdbc/criteria/KNativeSqlSelectTest.kt
  integration-test-java/src/test/java/org/seasar/doma/it/criteria/CustomExpressions.java
  integration-test-java/src/test/java/org/seasar/doma/it/criteria/NativeSqlSelectTest.java
  integration-test-java/src/test/java/org/seasar/doma/it/criteria/NativeSqlUpdateTest.java
Labels: feature

#1110 Improving KJoinDeclaration
  doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/declaration/KJoinDeclaration.kt
  doma-kotlin/src/test/kotlin/org/seasar/doma/jdbc/criteria/KNativeSqlSelectTest.kt
Labels: feature

#1111 Add the openStream method to the Criteria API to return a Stream
  doma-core/src/main/java/org/seasar/doma/jdbc/criteria/statement/NativeSqlSelectIntermediate.java
  doma-core/src/main/java/org/seasar/doma/jdbc/criteria/statement/NativeSqlSelectStarting.java
  doma-core/src/main/java/org/seasar/doma/jdbc/criteria/statement/NativeSqlSelectTerminal.java
  doma-core/src/main/java/org/seasar/doma/jdbc/criteria/statement/NativeSqlSetStarting.java
  doma-core/src/main/java/org/seasar/doma/jdbc/criteria/statement/NativeSqlSetTerminal.java
  doma-core/src/main/java/org/seasar/doma/jdbc/criteria/statement/StreamMappable.java
  doma-core/src/test/java/org/seasar/doma/jdbc/criteria/NativeSqlSelectTest.java
  doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/statement/KNativeSqlSelectIntermediate.kt
  doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/statement/KNativeSqlSelectStarting.kt
  doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/statement/KNativeSqlSetStarting.kt
  doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/statement/KSequenceMappable.kt
  doma-kotlin/src/test/kotlin/org/seasar/doma/jdbc/criteria/KNativeSqlSelectTest.kt
  integration-test-java/src/test/java/org/seasar/doma/it/criteria/NativeSqlSelectTest.java
  integration-test-kotlin/src/test/kotlin/org/seasar/doma/it/criteria/KNativeSqlSelectTest.kt
Labels: feature

#1112 Refactor UserDefinedExpression and related classes
  doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/Expressions.java
  doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/UserDefinedExpression.java
  doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/expression/KExpressions.kt
Labels: refactor
