Repository domaframework/doma, pull requests merged in 2024-07, with the labels that each got.

#1133 Reverse the supportsAutoGeneratedKeys flag in PostgresDialect
  doma-core/src/main/java/org/seasar/doma/jdbc/dialect/PostgresDialect.java
  doma-core/src/test/java/org/seasar/doma/jdbc/id/BuiltinIdentityIdGeneratorTest.java
Labels: chore

#1134 Enable removal of comments from SQL templates
  doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/SqlParser.java
  doma-core/src/main/java/org/seasar/doma/jdbc/AbstractSqlFileRepository.java
  doma-core/src/main/java/org/seasar/doma/jdbc/GreedyCacheSqlFileRepository.java
  doma-core/src/main/java/org/seasar/doma/jdbc/NoCacheSqlFileRepository.java
  doma-core/src/main/java/org/seasar/doma/jdbc/SqlParserConfig.java
  doma-core/src/test/java/org/seasar/doma/internal/jdbc/sql/SqlParserTest.java
  integration-test-common/src/main/java/org/seasar/doma/it/AppConfig.java
  integration-test-common/src/main/java/org/seasar/doma/it/LineCommentRemovalSqlParserConfig.java
  integration-test-java/src/main/resources/META-INF/org/seasar/doma/it/dao/EmployeeDao/selectById.sql
Labels: feature

#1132 Support multi-row insert
  doma-core/src/main/java/org/seasar/doma/MultiInsert.java
  doma-core/src/main/java/org/seasar/doma/jdbc/MultiResult.java
  doma-core/src/main/java/org/seasar/doma/jdbc/QueryImplementors.java
  doma-core/src/main/java/org/seasar/doma/jdbc/SqlExecutionSkipCause.java
  doma-core/src/main/java/org/seasar/doma/jdbc/SqlKind.java
  doma-core/src/main/java/org/seasar/doma/jdbc/criteria/Entityql.java
  doma-core/src/main/java/org/seasar/doma/jdbc/criteria/statement/EntityqlMultiInsertStatement.java
  doma-core/src/main/java/org/seasar/doma/jdbc/dialect/Dialect.java
  doma-core/src/main/java/org/seasar/doma/jdbc/dialect/MssqlDialect.java
  doma-core/src/main/java/org/seasar/doma/jdbc/dialect/Oracle11Dialect.java
  doma-core/src/main/java/org/seasar/doma/jdbc/entity/GeneratedIdPropertyType.java
  doma-core/src/main/java/org/seasar/doma/jdbc/id/AbstractPreGenerateIdGenerator.java
  doma-core/src/main/java/org/seasar/doma/jdbc/id/BuiltinIdentityIdGenerator.java
  doma-core/src/main/java/org/seasar/doma/jdbc/id/IdGenerator.java
  doma-core/src/main/java/org/seasar/doma/jdbc/query/AutoMultiInsertQuery.java
  doma-core/src/main/java/org/seasar/doma/message/Message.java
  doma-core/src/test/java/org/seasar/doma/jdbc/command/InsertCommandTest.java
  doma-core/src/test/java/org/seasar/doma/jdbc/criteria/EntityqlMultiInsertTest.java
  doma-core/src/test/java/org/seasar/doma/jdbc/query/AutoMultiInsertQueryTest.java
  doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/KEntityql.kt
  doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/statement/KEntityqlMultiInsertStatement.kt
  doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/statement/KEntityqlMultiUpsertStatement.kt
  doma-kotlin/src/test/kotlin/org/seasar/doma/jdbc/criteria/KEntityqlMultiInsertTest.kt
  doma-processor/src/main/java/org/seasar/doma/internal/apt/annot/Annotations.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/annot/MultiInsertAnnot.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/cttype/CtTypeVisitor.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/cttype/CtTypes.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/cttype/MultiResultCtType.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/cttype/SimpleCtTypeVisitor.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/generator/DaoImplQueryMethodGenerator.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/dao/DaoMetaFactory.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/AutoMultiInsertQueryMeta.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/AutoMultiInsertQueryMetaFactory.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/QueryKind.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/QueryMetaVisitor.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/QueryReturnMeta.java
  doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/AutoMultiInsertDao.java
  doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/DaoProcessorTest.java
  doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/MultiInsertIllegalParameterSizeDao.java
  doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/MultiInsertIllegalParameterTypeDao.java
  doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/MultiInsertIllegalReturnTypeDao.java
  doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/MultiInsertIllegalReturnTypeForImmutableEntityDao.java
  doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/MultiInsertIllegalTypeArgumentDao.java
  doma-processor/src/test/resources/org/seasar/doma/internal/apt/processor/dao/DaoProcessorTest_AutoMultiInsertDao.txt
  integration-test-java/src/main/java/org/seasar/doma/it/dao/BranchDao.java
  integration-test-java/src/main/java/org/seasar/doma/it/dao/BusinessmanDao.java
  integration-test-java/src/main/java/org/seasar/doma/it/dao/CompKeyDepartmentDao.java
  integration-test-java/src/main/java/org/seasar/doma/it/dao/DepartmentDao.java
  integration-test-java/src/main/java/org/seasar/doma/it/dao/DeptDao.java
  integration-test-java/src/main/java/org/seasar/doma/it/dao/IdentityStrategyDao.java
  integration-test-java/src/main/java/org/seasar/doma/it/dao/NoIdDao.java
  integration-test-java/src/main/java/org/seasar/doma/it/dao/PrimitiveIdentityStrategyDao.java
  integration-test-java/src/main/java/org/seasar/doma/it/dao/SequenceStrategyDao.java
  integration-test-java/src/main/java/org/seasar/doma/it/dao/StaffDao.java
  integration-test-java/src/main/java/org/seasar/doma/it/dao/TableStrategyDao.java
  integration-test-java/src/main/java/org/seasar/doma/it/dao/WorkerDao.java
  integration-test-java/src/test/java/org/seasar/doma/it/auto/AutoMultiInsertTest.java
  integration-test-java/src/test/java/org/seasar/doma/it/criteria/EntityqlMultiInsertTest.java
Labels: feature

#1135 Enable removal of blank lines from SQL templates
  build.gradle.kts
  doma-core/src/main/java/org/seasar/doma/internal/RuntimeConfig.java
  doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/NodePreparedSqlBuilder.java
  doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/node/BlankNode.java
  doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/node/EolNode.java
  doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/node/WhitespaceNode.java
  doma-core/src/main/java/org/seasar/doma/jdbc/Config.java
  doma-core/src/main/java/org/seasar/doma/jdbc/ConfigSupport.java
  doma-core/src/main/java/org/seasar/doma/jdbc/SqlBuilderSettings.java
  settings.gradle.kts
  unit-test/.gitignore
  unit-test/build.gradle.kts
  unit-test/src/test/java/org/seasar/doma/ut/BlankLineRemovalContextTest.java
  unit-test/src/test/java/org/seasar/doma/ut/BlankLineRemovalSqlParserTest.java
  unit-test/src/test/java/org/seasar/doma/ut/MockConfig.java
Labels: refactor

#1140 Reimplement "Enable removal of comments from SQL templates"
  doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/NodePreparedSqlBuilder.java
  doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/SqlParser.java
  doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/node/CommentNode.java
  doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/node/CommentType.java
  doma-core/src/main/java/org/seasar/doma/jdbc/AbstractSqlFileRepository.java
  doma-core/src/main/java/org/seasar/doma/jdbc/Config.java
  doma-core/src/main/java/org/seasar/doma/jdbc/GreedyCacheSqlFileRepository.java
  doma-core/src/main/java/org/seasar/doma/jdbc/NoCacheSqlFileRepository.java
  doma-core/src/main/java/org/seasar/doma/jdbc/SqlBuilderSettings.java
  doma-core/src/main/java/org/seasar/doma/jdbc/SqlParserConfig.java
  doma-core/src/test/java/org/seasar/doma/internal/jdbc/sql/SqlParserTest.java
  integration-test-common/src/main/java/org/seasar/doma/it/AppConfig.java
  integration-test-common/src/main/java/org/seasar/doma/it/LineCommentRemovalSqlParserConfig.java
  integration-test-java/src/main/resources/META-INF/org/seasar/doma/it/dao/EmployeeDao/selectById.sql
  unit-test/src/test/java/org/seasar/doma/ut/BlankLineRemovalContextTest.java
  unit-test/src/test/java/org/seasar/doma/ut/BlankLineRemovalSqlParserTest.java
  unit-test/src/test/java/org/seasar/doma/ut/CommentRemovalContextTest.java
Labels: feature

#1141 Prevent unintentionally nullable values in doma-kotlin.
  doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/KEntityql.kt
  doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/KNativeSql.kt
Labels: feature

#1145 Prevent unintentionally nullable values in KEntityql#insertMulti
  doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/KEntityql.kt
Labels: feature

#1142 Improving KSetDeclaration
  doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/declaration/KSetDeclaration.kt
Labels: feature

#1143 Improving KExpressions
  doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/expression/KExpressions.kt
  doma-kotlin/src/test/kotlin/org/seasar/doma/jdbc/criteria/KNativeSqlSelectTest.kt
Labels: feature
