Repository domaframework/doma, pull requests merged in 2024-08, with the labels that each got.

#1149 Enhance Multi-row Insert Support for H2, SQL Server, and Oracle Database
  doma-core/src/main/java/org/seasar/doma/jdbc/dialect/Dialect.java
  doma-core/src/main/java/org/seasar/doma/jdbc/dialect/H2UpsertAssembler.java
  doma-core/src/main/java/org/seasar/doma/jdbc/dialect/MssqlUpsertAssembler.java
  doma-core/src/main/java/org/seasar/doma/jdbc/dialect/MysqlUpsertAssembler.java
  doma-core/src/main/java/org/seasar/doma/jdbc/dialect/OracleDialect.java
  doma-core/src/main/java/org/seasar/doma/jdbc/dialect/OracleMultiInsertAssembler.java
  doma-core/src/main/java/org/seasar/doma/jdbc/dialect/OracleUpsertAssembler.java
  doma-core/src/main/java/org/seasar/doma/jdbc/dialect/PostgreSqlUpsertAssembler.java
  doma-core/src/main/java/org/seasar/doma/jdbc/dialect/StandardDialect.java
  doma-core/src/main/java/org/seasar/doma/jdbc/dialect/StandardMultiInsertAssembler.java
  doma-core/src/main/java/org/seasar/doma/jdbc/query/AutoMultiInsertQuery.java
  doma-core/src/main/java/org/seasar/doma/jdbc/query/InsertRow.java
  doma-core/src/main/java/org/seasar/doma/jdbc/query/MultiInsertAssembler.java
  doma-core/src/main/java/org/seasar/doma/jdbc/query/MultiInsertAssemblerContext.java
  doma-core/src/main/java/org/seasar/doma/jdbc/query/MultiInsertAssemblerContextBuilder.java
  doma-core/src/main/java/org/seasar/doma/jdbc/query/QueryOperandPairList.java
  doma-core/src/main/java/org/seasar/doma/jdbc/query/QueryRows.java
  doma-core/src/main/java/org/seasar/doma/jdbc/query/UpsertAssemblerContext.java
  doma-core/src/main/java/org/seasar/doma/jdbc/query/UpsertAssemblerContextBuilder.java
  doma-core/src/test/java/org/seasar/doma/jdbc/query/AutoMultiInsertQueryTest.java
  doma-core/src/test/java/org/seasar/doma/jdbc/query/UpsertAssemblerContextBuilderTest.java
  integration-test-java/src/test/java/org/seasar/doma/it/auto/AutoMultiInsertTest.java
  integration-test-java/src/test/java/org/seasar/doma/it/criteria/EntityqlMultiInsertTest.java
Labels: feature

#1146 Support upsert with insertMulti in doma-kotlin
  doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/statement/KEntityqlMultiInsertStatement.kt
  doma-kotlin/src/test/kotlin/org/seasar/doma/jdbc/criteria/KEntityqlInsertMultiTest.kt
Labels: feature

#1150 Add `duplicateKeys` property to `Insert`, `BatchInsert`, and `MultiInsert` annotations
  .gitignore
  doma-core/src/main/java/org/seasar/doma/BatchInsert.java
  doma-core/src/main/java/org/seasar/doma/Insert.java
  doma-core/src/main/java/org/seasar/doma/MultiInsert.java
  doma-core/src/main/java/org/seasar/doma/jdbc/query/AutoBatchInsertQuery.java
  doma-core/src/main/java/org/seasar/doma/jdbc/query/AutoInsertQuery.java
  doma-core/src/main/java/org/seasar/doma/jdbc/query/AutoMultiInsertQuery.java
  doma-core/src/main/java/org/seasar/doma/jdbc/query/UpsertAssemblerContextBuilder.java
  doma-core/src/main/java/org/seasar/doma/message/Message.java
  doma-core/src/test/java/org/seasar/doma/jdbc/query/AutoBatchInsertQueryTest.java
  doma-core/src/test/java/org/seasar/doma/jdbc/query/AutoInsertQueryTest.java
  doma-core/src/test/java/org/seasar/doma/jdbc/query/AutoMultiInsertQueryTest.java
  doma-core/src/test/java/org/seasar/doma/jdbc/query/UpsertAssemblerContextBuilderTest.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/annot/BatchModifyAnnot.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/annot/ModifyAnnot.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/annot/MultiInsertAnnot.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/generator/DaoImplQueryMethodGenerator.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/AbstractQueryMetaFactory.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/AutoBatchModifyQueryMeta.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/AutoBatchModifyQueryMetaFactory.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/AutoModifyQueryMeta.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/AutoModifyQueryMetaFactory.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/AutoMultiInsertQueryMeta.java
  doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/AutoMultiInsertQueryMetaFactory.java
  doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/AutoInsertDao.java
  doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/AutoMultiInsertDao.java
  doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/BatchInsertIllegalDuplicateKeyDao.java
  doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/DaoProcessorTest.java
  doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/InsertIllegalDuplicateKeyDao.java
  doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/MultiInsertIllegalDuplicateKeyDao.java
  doma-processor/src/test/resources/org/seasar/doma/internal/apt/processor/dao/DaoProcessorTest_AnnotateWithDao.txt
  doma-processor/src/test/resources/org/seasar/doma/internal/apt/processor/dao/DaoProcessorTest_AnnotationConfigDao.txt
  doma-processor/src/test/resources/org/seasar/doma/internal/apt/processor/dao/DaoProcessorTest_AutoInsertDao.txt
  doma-processor/src/test/resources/org/seasar/doma/internal/apt/processor/dao/DaoProcessorTest_AutoMultiInsertDao.txt
  doma-processor/src/test/resources/org/seasar/doma/internal/apt/processor/dao/DaoProcessorTest_ConfigAnnotateWithDao.txt
  doma-processor/src/test/resources/org/seasar/doma/internal/apt/processor/dao/DaoProcessorTest_IgnoreGeneratedKeysDao.txt
  doma-processor/src/test/resources/org/seasar/doma/internal/apt/processor/dao/DaoProcessorTest_ImmutableEmpDao.txt
  doma-processor/src/test/resources/org/seasar/doma/internal/apt/processor/dao/DaoProcessorTest_MultipleAnnotateWithDao.txt
  doma-processor/src/test/resources/org/seasar/doma/internal/apt/processor/dao/DaoProcessorTest_NoConfigDao.txt
  doma-processor/src/test/resources/org/seasar/doma/internal/apt/processor/dao/DaoProcessorTest_PackageAccessLevelDao.txt
  integration-test-java/src/main/java/org/seasar/doma/it/dao/DeptDao.java
  integration-test-java/src/main/resources/META-INF/org/seasar/doma/it/dao/DeptDao/selectByDepartmentNo.sql
  integration-test-java/src/test/java/org/seasar/doma/it/auto/AutoBatchInsertTest.java
  integration-test-java/src/test/java/org/seasar/doma/it/auto/AutoInsertTest.java
  integration-test-java/src/test/java/org/seasar/doma/it/auto/AutoMultiInsertTest.java
Labels: feature

#1153 Fix KJoinDeclaration
  doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/declaration/KJoinDeclaration.kt
Labels: feature

#1163 Add the upload artifact action to codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: ci

#1164 Fix CodeQL build failure
  doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/metamodel/ScopeTest.java
Labels: ci

#1165 Fix CodeQL build failure
  .github/workflows/codeql-analysis.yml
  doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/metamodel/ScopeTest.java
Labels: ci

#1167 Fix issue with duplicate log output in the integration test projects
  integration-test-common/src/main/java/org/seasar/doma/it/LogConfigurator.java
Labels: chore

#1169 Change the branch name in workflow files
  .github/workflows/ci.yml
  .github/workflows/release-draft.yml
Labels: ci

#1171 Configure the settings for releasing version 2.x
  .github/workflows/release-draft.yml
  .github/workflows/release.yml
  build.gradle.kts
Labels: ci

#1172 Update google-java-format to v1.23.0
  build.gradle.kts
  doma-core/src/test/java/org/seasar/doma/internal/jdbc/sql/BlankLineRemovalContextTest.java
  doma-core/src/test/java/org/seasar/doma/internal/jdbc/sql/CommentRemovalContextTest.java
  integration-test-java/src/main/java/org/seasar/doma/it/jep355/TextBlockDao.java
  integration-test-java/src/main/java/org/seasar/doma/it/jep384/RecordDao.java
Labels: dependencies

#1173 Update H2 Database Engine to v2.3.232
  build.gradle.kts
  doma-core/src/main/java/org/seasar/doma/internal/jdbc/dialect/H2PagingTransformer.java
  doma-core/src/test/java/org/seasar/doma/internal/jdbc/dialect/H2PagingTransformerTest.java
  integration-test-common/src/main/resources/META-INF/org/seasar/doma/it/dao/ScriptDao/create-db2.script
  integration-test-common/src/main/resources/META-INF/org/seasar/doma/it/dao/ScriptDao/create-h2.script
  integration-test-common/src/main/resources/META-INF/org/seasar/doma/it/dao/ScriptDao/create-hsqldb.script
  integration-test-common/src/main/resources/META-INF/org/seasar/doma/it/dao/ScriptDao/create-mssql.script
  integration-test-common/src/main/resources/META-INF/org/seasar/doma/it/dao/ScriptDao/create-mssql2008.script
  integration-test-common/src/main/resources/META-INF/org/seasar/doma/it/dao/ScriptDao/create-mysql.script
  integration-test-common/src/main/resources/META-INF/org/seasar/doma/it/dao/ScriptDao/create-oracle.script
  integration-test-common/src/main/resources/META-INF/org/seasar/doma/it/dao/ScriptDao/create-postgres.script
  integration-test-common/src/main/resources/META-INF/org/seasar/doma/it/dao/ScriptDao/create-sqlite.script
  integration-test-java/src/main/java/org/seasar/doma/it/criteria/IdentityTable.java
  integration-test-java/src/main/java/org/seasar/doma/it/dao/RoomDao.java
  integration-test-java/src/main/java/org/seasar/doma/it/domain/StringArrayConverter.java
  integration-test-java/src/main/java/org/seasar/doma/it/entity/IdentityStrategy.java
  integration-test-java/src/main/java/org/seasar/doma/it/entity/IdentityStrategy2.java
  integration-test-java/src/main/java/org/seasar/doma/it/entity/PrimitiveIdentityStrategy.java
  integration-test-java/src/main/java/org/seasar/doma/it/entity/SequenceStrategy.java
  integration-test-java/src/main/java/org/seasar/doma/it/entity/TableStrategy.java
Labels: dependencies

#1174 Update Oracle JDBC driver and Docker image
  build.gradle.kts
  gradle.properties
Labels: dependencies

#1175 Update SQL Server JDBC driver to 12.8.1.jre11
  build.gradle.kts
Labels: dependencies

#1176 Update PostgreSQL Docker image to 12.20
  gradle.properties
Labels: dependencies

#1177 Update README.md and RELEASE_OPERATIONS.md
  README.md
  RELEASE_OPERATIONS.md
Labels: docs

#1178 Polish the build.gradle.kts file
  build.gradle.kts
Labels: chore

#1179 Polish README.md
  README.md
Labels: docs
